// puzzles.js — generated by scrape_v2.py
// Source: play.xiangqi.com  Theme: checkmate  Turn: red

export const PUZZLES = [
  {
    id: 1,
    title: "Chiều hết trong 1 nước",
    movesToMate: 1,
    turn: "red",
    // fen: 2bak4/1N2a4/4b4/2PR5/9/P8/8P/4B4/5r2n/3K2B2 w - - 6 46
    // source: onVw5o
    pieces: [{"type": "E", "color": "black", "col": 2, "row": 0}, {"type": "A", "color": "black", "col": 3, "row": 0}, {"type": "G", "color": "black", "col": 4, "row": 0}, {"type": "H", "color": "red", "col": 1, "row": 1}, {"type": "A", "color": "black", "col": 4, "row": 1}, {"type": "E", "color": "black", "col": 4, "row": 2}, {"type": "P", "color": "red", "col": 2, "row": 3}, {"type": "R", "color": "red", "col": 3, "row": 3}, {"type": "P", "color": "red", "col": 0, "row": 5}, {"type": "P", "color": "red", "col": 8, "row": 6}, {"type": "E", "color": "red", "col": 4, "row": 7}, {"type": "R", "color": "black", "col": 5, "row": 8}, {"type": "H", "color": "black", "col": 8, "row": 8}, {"type": "G", "color": "red", "col": 3, "row": 9}, {"type": "E", "color": "red", "col": 6, "row": 9}],
    solution: [{"fromCol": 3, "fromRow": 3, "toCol": 3, "toRow": 8}, {"fromCol": 5, "fromRow": 8, "toCol": 5, "toRow": 9}],
  },
  {
    id: 2,
    title: "Chiều hết trong 1 nước",
    movesToMate: 1,
    turn: "red",
    // fen: 2baka3/5r3/n3b3N/p1p3p1p/9/4n4/P1P3P1P/3RK1N2/1r7/2BA1ABR1 w - - 18 21
    // source: R67Pyo
    pieces: [{"type": "E", "color": "black", "col": 2, "row": 0}, {"type": "A", "color": "black", "col": 3, "row": 0}, {"type": "G", "color": "black", "col": 4, "row": 0}, {"type": "A", "color": "black", "col": 5, "row": 0}, {"type": "R", "color": "black", "col": 5, "row": 1}, {"type": "H", "color": "black", "col": 0, "row": 2}, {"type": "E", "color": "black", "col": 4, "row": 2}, {"type": "H", "color": "red", "col": 8, "row": 2}, {"type": "P", "color": "black", "col": 0, "row": 3}, {"type": "P", "color": "black", "col": 2, "row": 3}, {"type": "P", "color": "black", "col": 6, "row": 3}, {"type": "P", "color": "black", "col": 8, "row": 3}, {"type": "H", "color": "black", "col": 4, "row": 5}, {"type": "P", "color": "red", "col": 0, "row": 6}, {"type": "P", "color": "red", "col": 2, "row": 6}, {"type": "P", "color": "red", "col": 6, "row": 6}, {"type": "P", "color": "red", "col": 8, "row": 6}, {"type": "R", "color": "red", "col": 3, "row": 7}, {"type": "G", "color": "red", "col": 4, "row": 7}, {"type": "H", "color": "red", "col": 6, "row": 7}, {"type": "R", "color": "black", "col": 1, "row": 8}, {"type": "E", "color": "red", "col": 2, "row": 9}, {"type": "A", "color": "red", "col": 3, "row": 9}, {"type": "A", "color": "red", "col": 5, "row": 9}, {"type": "E", "color": "red", "col": 6, "row": 9}, {"type": "R", "color": "red", "col": 7, "row": 9}],
    solution: [{"fromCol": 6, "fromRow": 7, "toCol": 4, "toRow": 6}, {"fromCol": 4, "fromRow": 5, "toCol": 6, "toRow": 6}],
  },
];
